//Common Macros

`define SIMULATION
`define MAX_NUM_USB_DEVICES 16
`define WIDTH_TO_RANGE(width) width-1:0
//Usage: `def <MY_RANGE> `WIDTH_TO_RANGE(WIDTH_PARAMETER)

`define REQUEST_SERIAL_DATA_TYPE_WIDTH 3
`define REQUEST_SERIAL_DATA_TYPE_RANGE `WIDTH_TO_RANGE(`REQUEST_SERIAL_DATA_TYPE_WIDTH)
`define REQUEST_SERIAL_DATA_TYPE_NULL  `REQUEST_SERIAL_DATA_TYPE_WIDTH'h0
`define REQUEST_SERIAL_DATA_TYPE_SYNC  `REQUEST_SERIAL_DATA_TYPE_WIDTH'h1
`define REQUEST_SERIAL_DATA_TYPE_PID   `REQUEST_SERIAL_DATA_TYPE_WIDTH'h2
`define REQUEST_SERIAL_DATA_TYPE_READ  `REQUEST_SERIAL_DATA_TYPE_WIDTH'h3
`define REQUEST_SERIAL_DATA_TYPE_PASS  `REQUEST_SERIAL_DATA_TYPE_WIDTH'h4
`define REQUEST_SERIAL_DATA_TYPE_ACK   `REQUEST_SERIAL_DATA_TYPE_WIDTH'h5


`define ERROR(input_string)\
  $display("RTL Error: %s, from Module %m", input_string); \
  $finish

parameter USB_TR_STATE_TOGGLE
parameter USB_TR_STATE_IDLE
parameter USB_TR_STATE_Z